### PR TITLE
Verify invariants

### PR DESCRIPTION
**Pull request by nilehmann**
closes https://github.com/liquid-rust/flux/issues/165

Verify that `#[flux::invariant(...)]` annotations actually hold. Closes https://github.com/liquid-rust/flux/issues/165

To verify if an invariant holds for an ADT, we check for each variant/constructor that the invariant holds for the indices in the output, assuming all the preconditions that can be extracted from the arguments (this calls the unpack function in RefineCtxt). This includes invariants on the input types (which can be recursive). Each invariant is proven in isolation, but when extracting the preconditions other invariants on the input types can be assumed. I'm unsure if this is actually sound when there are complex interactions between invariants and/or mutually recursive types.

### CODE REVIEW

**Comment by nilehmann** [comment]
@ranjitjhala can you comment on the strategy?

**Comment by nilehmann** [comment]
I'm just going to merge this as I think it is already an improvement over completely unverified invariants. We can revisit later and now I'm mostly worried about getting in the necessary infrastructure to verify the invariants.

**Comment by ranjitjhala** [comment]
👍🏽

**Comment by ranjitjhala** [comment]
@nilehmann shouldn't we also check e.g. that the output type is _not_ constrained? AFAICT this is silently still allowed?


```rust
#![feature(register_tool)]
#![register_tool(flux)]

#[flux::refined_by(n:int)]
pub enum List<T> {
    #[flux::variant(List<T>[0])]
    Nil,
    #[flux::variant({T, Box<List<T>[@n]>} -> {List<T>[n+1]: 100 <= n})]
    Cons(T, Box<List<T>>),
}
```

Should we keep #165 open till this is plugged?

**Comment by nilehmann** [comment]
@ranjitjhala yeah, even more restrictive the output can only be an indexed type. I think we can enforce that syntactically. I'll open a new issue.

**Comment by nilehmann** [comment]
As a side note of we enforce it syntactically I think we could get rid of the curly braces and use normal parentheses.

**Pull request merged**
